#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

handle_error() {
    trap '' ERR
    local frame=0 str
    local stacktrace="Command exited with status $1\n\nStack:"
    while str=$(caller $frame); do
        stacktrace+="\nline $str"
        frame=$((frame + 1))
    done
    notify-send -u critical "hlwm config error" "$stacktrace"
}
set -o errtrace
trap 'handle_error $?' ERR

# kill all old sub processes
[[ -n "$HLWM_PID" ]] && pkill -P "$HLWM_PID"
export HLWM_PID="$$"
hc emit_hook reload

for f in "$(dirname "$0")"/hlwm.d/*.sh; do
    if [[ -x "$f" ]]; then
        "$f"
    fi
done

hc unlock
