--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baba/.local/share/wallpapers/wallhaven-yq752d.jpg"

-- Special
background="#212019"
foreground="#eee5c6"
cursor="#b4ae92"

-- Colors
color0="#212019"
color1="#3e3d31"
color2="#5b5a48"
color3="#797660"
color4="#969279"
color5="#b4ae92"
color6="#d1c9ac"
color7="#eee5c6"
color8="#a6a581"
color9="#a6a647"
color10="#a99c61"
color11="#aa6c30"
color12="#aa9336"
color13="#8baa64"
color14="#c6b892"
color15="#c7bfa5"
