--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baba/.local/share/wallpapers/gruvbox_astro.jpg"

-- Special
background="#13211e"
foreground="#cf7a6d"
cursor="#9d9655"

-- Colors
color0="#13211e"
color1="#21392b"
color2="#2e5230"
color3="#4c6b3c"
color4="#738449"
color5="#9d9655"
color6="#b68d61"
color7="#cf7a6d"
color8="#60a598"
color9="#a6a26c"
color10="#a4a6a2"
color11="#89a5a6"
color12="#a8a290"
color13="#aa8287"
color14="#ab9947"
color15="#ad665b"
