#!/bin/bash

handle_error() {
    trap '' ERR
    local frame=0 str
    local stacktrace="Command exited with status $1\n\nStack:"
    while str=$(caller $frame); do
        stacktrace+="\nline $str"
        frame=$((frame + 1))
    done
    notify-send -u critical "hlwm config error" "$stacktrace"
}
set -o errtrace
trap 'handle_error $?' ERR

# source ~/.cache/flavours/co
xsetroot -cursor_name left_ptr

pgrep sxhkd > /dev/null || sxhkd -c "$HOME/.config/sxhkd/bspwmrc" &
########
#CONFIG#
########
bspc monitor -d home web dev music games

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus false

# bspc config normal_border_color "$color7"
# bspc config active_border_color "$color8"
# bspc config focused_border_color "$color9"
# bspc config presel_feedback_color "$color10"

bspc desktop games -l monocle

#######
#RULES#
#######

declare -A shifts
shifts[firefox]="web"
shifts[steam]="games"
shifts[Lutris]="games"
shifts[Discord]="games"
shifts[REAPER]="music"
shifts[com.bitwig.BitwigStudio]="music"
shifts[Qtractor]="music"
shifts[Spotify]="music"
for key in "${!shifts[@]}"; do
    bspc rule -a "$key" desktop="${shifts[$key]}"
done 

bspc rule -a Pcmanfm state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Zenity state=floating
bspc rule -a "steam:*:Friends List" state=floating

bspc rule -a firefox:Toolkit:Picture-in-Picture state=floating sticky=on
