#!/bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd >/dev/null || sxhkd &

########
#CONFIG#
########
bspc monitor -d     

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

#######
#RULES#
#######

bspc rule -a polybar:Polybar manage=off

bspc rule -a firefox desktop=
bspc rule -a steam desktop= focus=off
bspc rule -a Lutris desktop= focus=off
bspc rule -a REAPER desktop= focus=off
bspc rule -a com.bitwig.BitwigStudio desktop= focus=off
bspc rule -a Qtractor desktop= focus=off
bspc rule -a Spotify desktop= focus=off
bspc rule -a discord desktop= focus=off

bspc rule -a Pcmanfm state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Zenity state=floating
bspc rule -a "steam:*:Friends List" state=floating

bspc rule -a firefox:Toolkit:* state=floating sticky=on
