#!/bin/sh

xsetroot -cursor_name left_ptr
if [[ "$1" -eq 0 ]]; then
  sxhkd &
  dunst &
  picom -b
  polybar &
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
  nitrogen --restore &
  dex -a -w &
fi
notify-send "Session load complete!"

########
#CONFIG#
########
bspc monitor -d home web dev music games

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config normal_border_color "#282A36"
bspc config active_border_color "#44475A"
bspc config focused_border_color "#44475A"
bspc config presel_feedback_color "#BD93F9"

bspc desktop games -l monocle

#######
#RULES#
#######

bspc rule -a polybar:Polybar manage=off

bspc rule -a firefox desktop=web
bspc rule -a steam desktop=games focus=off
bspc rule -a Lutris desktop=games focus=off
bspc rule -a Discord desktop=games focus=off
bspc rule -a REAPER desktop=music focus=off
bspc rule -a com.bitwig.BitwigStudio desktop=music focus=off
bspc rule -a Qtractor desktop=music focus=off
bspc rule -a Spotify desktop=music focus=off

bspc rule -a Pcmanfm state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Zenity state=floating
bspc rule -a "steam:*:Friends List" state=floating

bspc rule -a firefox:Toolkit:* state=floating sticky=on
